#!/usr/bin/env bash
cd /usr/local/spark

HOSTNAME=`hostname`
export HOST_IP=`getent hosts $HOSTNAME | cut -d' ' -f1`

export SPARK_LOCAL_IP=$HOST_IP
./bin/spark-class org.apache.spark.deploy.worker.Worker \
	spark://${SPARK_MASTER_PORT_7077_TCP_ADDR}:${SPARK_MASTER_ENV_SPARK_MASTER_PORT} \
	--properties-file /spark-defaults.conf \
	-i $SPARK_LOCAL_IP \
	"$@"
